<a href="https://colab.research.google.com/github/Heng1222/VeriPromiseESG_2026_TEAM_9906/blob/feat-model-train/app/model/model_train.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# CKIP-BERT Multi-Task Fine-Tuning

This notebook fine-tunes one `ckiplab/bert-base-chinese` model per fold with the existing shared-backbone and four-MLP-head architecture.

Key properties:

- External inference input remains `id,data`.
- Submission output remains `id,promise_status,verification_timeline,evidence_status,evidence_quality`.
- The masked BCE/CE objective and competition task weights are retained.
- Five folds are used both for reliable OOF evaluation and lower-variance probability ensembling.
- Each fold saves the epoch with the highest validation competition macro-F1, rather than the last epoch.
- Existing synthetic `Misleading` rows train T4 only and cannot alter T1-T3.

In [1]:
# Install dependencies in Colab, then restart the runtime if requested.
# !pip install -q transformers torch pandas numpy scikit-learn tqdm huggingface_hub

In [2]:
import gc
import json
import math
import os
import random
import warnings
from pathlib import Path

import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from huggingface_hub import HfApi, notebook_login
from sklearn.metrics import classification_report, confusion_matrix, f1_score
from torch.utils.data import DataLoader, Dataset
from tqdm.auto import tqdm
from transformers import AutoModel, AutoTokenizer, get_cosine_schedule_with_warmup

warnings.filterwarnings("ignore")

In [17]:
# ==========================================
# 0. Configuration
# ==========================================

MODEL_NAME = "ckiplab/bert-base-chinese"
FOLDS = [1, 2, 3, 4, 5]
SEED = 42

MAX_LEN = 512
HEAD_RATIO = 0.25
BATCH_SIZE = 8
GRAD_ACCUM_STEPS = 2
MAX_EPOCHS = 10
EARLY_STOPPING_PATIENCE = 2
MIN_SCORE_IMPROVEMENT = 1e-4

BACKBONE_LR = 1.5e-5
HEAD_LR = 7.5e-5
WEIGHT_DECAY = 0.01
WARMUP_RATIO = 0.10
MAX_GRAD_NORM = 1.0

SYNTHETIC_ID_MIN = 90000
SYNTHETIC_T4_SAMPLE_WEIGHT = 0.35
MAX_CLASS_WEIGHT = 5.0

TASK_WEIGHTS = {
    "t1": 0.20,
    "t2": 0.15,
    "t3": 0.30,
    "t4": 0.35,
}

ID_COLUMN = "id"
TEXT_COLUMN = "data"
TARGET_COLUMNS = [
    "promise_status",
    "verification_timeline",
    "evidence_status",
    "evidence_quality",
]

TASK_CLASSES = {
    "t1": ["No", "Yes"],
    "t2": ["already", "within_2_years", "between_2_and_5_years", "longer_than_5_years"],
    "t3": ["No", "Yes"],
    "t4": ["Clear", "Not Clear", "Misleading"],
}

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
USE_AMP = DEVICE.type == "cuda"

PROJECT_ROOT = Path.cwd().resolve()
for candidate in [PROJECT_ROOT, *PROJECT_ROOT.parents]:
    if (candidate / "app" / "data" / "clean_data").exists():
        PROJECT_ROOT = candidate
        break

LOCAL_DATA_DIR = PROJECT_ROOT / "app" / "data" / "clean_data"
RAW_BASE_URL = "https://raw.githubusercontent.com/Heng1222/VeriPromiseESG_2026_TEAM_9906/feat-model-train/app/data/clean_data/"

OUTPUT_DIR = Path("mtl_outputs")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
OOF_PROBABILITY_CSV = OUTPUT_DIR / "mtl_oof_probabilities.csv"
OOF_PREDICTION_CSV = OUTPUT_DIR / "mtl_oof_predictions.csv"
THRESHOLD_JSON = OUTPUT_DIR / "mtl_thresholds.json"
INFERENCE_CONFIG_JSON = OUTPUT_DIR / "mtl_inference_config.json"
TOKENIZER_DIR = OUTPUT_DIR / "tokenizer"

RUN_HF_UPLOAD = True
HF_MTL_REPO_ID = "maxbeettww/VeriPromise_ESG_2026_9906"
HF_PRIVATE_REPO = False
HF_COMMIT_MESSAGE = "Upload CKIP-BERT MTL artifacts"

print(f"Device: {DEVICE}")
print(f"Project root: {PROJECT_ROOT}")

Device: cuda
Project root: /home/public/zhengheng/VeriPromiseESG_2026_TEAM_9906

In [4]:
# ==========================================
# 1. Data loading and tokenization
# ==========================================

def set_seed(seed):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False


def normalize_value(value):
    if pd.isna(value):
        return None
    value = str(value).strip()
    if not value or value.upper() == "N/A":
        return None
    if value == "more_than_5_years":
        return "longer_than_5_years"
    return value


def read_fold_csv(fold, split):
    filename = f"{split}_fold_{fold}.csv"
    local_path = LOCAL_DATA_DIR / filename
    if local_path.exists():
        return pd.read_csv(local_path)
    return pd.read_csv(f"{RAW_BASE_URL}{filename}")


def validate_training_frame(df, name):
    required = [ID_COLUMN, TEXT_COLUMN] + TARGET_COLUMNS
    missing = [column for column in required if column not in df.columns]
    if missing:
        raise ValueError(f"{name} missing columns: {missing}")
    if df[ID_COLUMN].duplicated().any():
        raise ValueError(f"{name} contains duplicated ids.")


def tokenize_head_tail(text, tokenizer, max_len=MAX_LEN, head_ratio=HEAD_RATIO):
    body_ids = tokenizer.encode(
        f"文本：{str(text)}",
        add_special_tokens=False,
        verbose=False,
    )
    max_body_len = max_len - 2
    if len(body_ids) > max_body_len:
        head_len = int(max_body_len * head_ratio)
        tail_len = max_body_len - head_len
        body_ids = body_ids[:head_len] + body_ids[-tail_len:]

    input_ids = [tokenizer.cls_token_id] + body_ids + [tokenizer.sep_token_id]
    attention_mask = [1] * len(input_ids)
    pad_len = max_len - len(input_ids)
    input_ids += [tokenizer.pad_token_id] * pad_len
    attention_mask += [0] * pad_len
    return input_ids, attention_mask


class ESGMTLDataset(Dataset):
    T1_MAP = {"No": 0, "Yes": 1}
    T2_MAP = {
        "already": 0,
        "within_2_years": 1,
        "between_2_and_5_years": 2,
        "longer_than_5_years": 3,
        "more_than_5_years": 3,
    }
    T3_MAP = {"No": 0, "Yes": 1}
    T4_MAP = {"Clear": 0, "Not Clear": 1, "Misleading": 2}

    def __init__(self, dataframe, tokenizer, max_len=MAX_LEN, is_test=False):
        self.df = dataframe.reset_index(drop=True)
        self.tokenizer = tokenizer
        self.max_len = max_len
        self.is_test = is_test

    def __len__(self):
        return len(self.df)

    def __getitem__(self, index):
        row = self.df.iloc[index]
        input_ids, attention_mask = tokenize_head_tail(
            row[TEXT_COLUMN],
            tokenizer=self.tokenizer,
            max_len=self.max_len,
        )
        item = {
            "input_ids": torch.tensor(input_ids, dtype=torch.long),
            "attention_mask": torch.tensor(attention_mask, dtype=torch.long),
            "row_index": torch.tensor(index, dtype=torch.long),
        }
        if self.is_test:
            return item

        is_synthetic = int(pd.to_numeric(row[ID_COLUMN], errors="coerce") >= SYNTHETIC_ID_MIN)
        t1_value = normalize_value(row.get("promise_status"))
        t2_value = normalize_value(row.get("verification_timeline"))
        t3_value = normalize_value(row.get("evidence_status"))
        t4_value = normalize_value(row.get("evidence_quality"))

        item.update(
            {
                "t1_label": torch.tensor(self.T1_MAP.get(t1_value, -1), dtype=torch.float),
                "t2_label": torch.tensor(self.T2_MAP.get(t2_value, -1), dtype=torch.long),
                "t3_label": torch.tensor(self.T3_MAP.get(t3_value, -1), dtype=torch.float),
                "t4_label": torch.tensor(self.T4_MAP.get(t4_value, -1), dtype=torch.long),
                "is_synthetic": torch.tensor(is_synthetic, dtype=torch.bool),
            }
        )
        return item

In [5]:
# ==========================================
# 2. Existing shared CKIP-BERT + four MLP heads
# ==========================================

class ESGUnifiedMTLModel(nn.Module):
    def __init__(self, model_name):
        super().__init__()
        self.backbone = AutoModel.from_pretrained(model_name)
        hidden_size = self.backbone.config.hidden_size

        self.multi_sample_dropouts = nn.ModuleList(
            [nn.Dropout(probability) for probability in [0.1, 0.2, 0.3, 0.4, 0.5]]
        )
        self.t1_head = nn.Sequential(
            nn.Linear(hidden_size, 16),
            nn.LayerNorm(16),
            nn.GELU(),
            nn.Dropout(0.2),
            nn.Linear(16, 1),
        )
        self.t3_head = nn.Sequential(
            nn.Linear(hidden_size, 16),
            nn.LayerNorm(16),
            nn.GELU(),
            nn.Dropout(0.2),
            nn.Linear(16, 1),
        )
        self.t2_head = nn.Sequential(
            nn.Linear(hidden_size, 32),
            nn.LayerNorm(32),
            nn.GELU(),
            nn.Dropout(0.2),
            nn.Linear(32, 4),
        )
        self.t4_head = nn.Sequential(
            nn.Linear(hidden_size, 32),
            nn.LayerNorm(32),
            nn.GELU(),
            nn.Dropout(0.2),
            nn.Linear(32, 3),
        )

    def forward(self, input_ids, attention_mask):
        outputs = self.backbone(input_ids=input_ids, attention_mask=attention_mask)
        cls_output = outputs.last_hidden_state[:, 0, :]

        # Preserve the existing heads while making the intended multi-sample dropout active.
        t1_logits = torch.stack(
            [self.t1_head(dropout(cls_output)).squeeze(-1) for dropout in self.multi_sample_dropouts]
        ).mean(dim=0)
        t3_logits = torch.stack(
            [self.t3_head(dropout(cls_output)).squeeze(-1) for dropout in self.multi_sample_dropouts]
        ).mean(dim=0)
        t2_logits = self.t2_head(cls_output)
        t4_logits = self.t4_head(cls_output)
        return t1_logits, t2_logits, t3_logits, t4_logits


def sqrt_class_weights(counts, max_weight=MAX_CLASS_WEIGHT):
    counts = np.asarray(counts, dtype=float)
    largest = counts.max()
    weights = np.sqrt(largest / np.maximum(counts, 1e-8))
    return np.minimum(weights, max_weight)


def compute_fold_class_weights(train_df):
    work = train_df.copy()
    for column in TARGET_COLUMNS:
        work[column] = work[column].apply(normalize_value)
    synthetic = pd.to_numeric(work[ID_COLUMN], errors="coerce") >= SYNTHETIC_ID_MIN

    t1_counts = [
        int(((work["promise_status"] == label) & ~synthetic).sum())
        for label in TASK_CLASSES["t1"]
    ]
    t2_counts = [
        int(((work["verification_timeline"] == label) & ~synthetic).sum())
        for label in TASK_CLASSES["t2"]
    ]
    t3_counts = [
        int(((work["evidence_status"] == label) & ~synthetic).sum())
        for label in TASK_CLASSES["t3"]
    ]
    t4_counts = []
    for label in TASK_CLASSES["t4"]:
        real_count = int(((work["evidence_quality"] == label) & ~synthetic).sum())
        synthetic_count = int(((work["evidence_quality"] == label) & synthetic).sum())
        t4_counts.append(real_count + SYNTHETIC_T4_SAMPLE_WEIGHT * synthetic_count)

    return {
        "t1": torch.tensor(sqrt_class_weights(t1_counts), dtype=torch.float, device=DEVICE),
        "t2": torch.tensor(sqrt_class_weights(t2_counts), dtype=torch.float, device=DEVICE),
        "t3": torch.tensor(sqrt_class_weights(t3_counts), dtype=torch.float, device=DEVICE),
        "t4": torch.tensor(sqrt_class_weights(t4_counts), dtype=torch.float, device=DEVICE),
    }


def weighted_mean(losses, weights):
    return (losses * weights).sum() / weights.sum().clamp_min(1e-8)


def calculate_mtl_loss(predictions, batch, class_weights):
    t1_logits, t2_logits, t3_logits, t4_logits = predictions
    t1_labels = batch["t1_label"].to(DEVICE)
    t2_labels = batch["t2_label"].to(DEVICE)
    t3_labels = batch["t3_label"].to(DEVICE)
    t4_labels = batch["t4_label"].to(DEVICE)
    is_synthetic = batch["is_synthetic"].to(DEVICE)

    zero = t1_logits.sum() * 0.0
    losses = {"t1": zero, "t2": zero, "t3": zero, "t4": zero}

    # Synthetic Misleading rows are allowed to teach T4 only.
    real_mask = ~is_synthetic
    t1_valid = real_mask & (t1_labels >= 0)
    if t1_valid.any():
        element_loss = nn.functional.binary_cross_entropy_with_logits(
            t1_logits[t1_valid],
            t1_labels[t1_valid],
            reduction="none",
        )
        sample_weight = class_weights["t1"][t1_labels[t1_valid].long()]
        losses["t1"] = weighted_mean(element_loss, sample_weight)

    t2_valid = real_mask & (t1_labels == 1) & (t2_labels >= 0)
    if t2_valid.any():
        losses["t2"] = nn.functional.cross_entropy(
            t2_logits[t2_valid],
            t2_labels[t2_valid],
            weight=class_weights["t2"],
        )

    t3_valid = real_mask & (t1_labels == 1) & (t3_labels >= 0)
    if t3_valid.any():
        element_loss = nn.functional.binary_cross_entropy_with_logits(
            t3_logits[t3_valid],
            t3_labels[t3_valid],
            reduction="none",
        )
        sample_weight = class_weights["t3"][t3_labels[t3_valid].long()]
        losses["t3"] = weighted_mean(element_loss, sample_weight)

    t4_valid = (t1_labels == 1) & (t3_labels == 1) & (t4_labels >= 0)
    if t4_valid.any():
        element_loss = nn.functional.cross_entropy(
            t4_logits[t4_valid],
            t4_labels[t4_valid],
            weight=class_weights["t4"],
            reduction="none",
        )
        sample_weight = torch.where(
            is_synthetic[t4_valid],
            torch.full_like(element_loss, SYNTHETIC_T4_SAMPLE_WEIGHT),
            torch.ones_like(element_loss),
        )
        losses["t4"] = weighted_mean(element_loss, sample_weight)

    total_loss = sum(TASK_WEIGHTS[task] * loss for task, loss in losses.items())
    return total_loss, losses

In [6]:
# ==========================================
# 3. Probability routing and competition metrics
# ==========================================

def sigmoid_numpy(values):
    values = np.clip(values, -30, 30)
    return 1.0 / (1.0 + np.exp(-values))


def softmax_numpy(values):
    shifted = values - values.max(axis=1, keepdims=True)
    exp_values = np.exp(shifted)
    return exp_values / exp_values.sum(axis=1, keepdims=True)


def predict_probabilities(model, data_loader):
    model.eval()
    output = {task: [] for task in ["t1", "t2", "t3", "t4"]}
    with torch.no_grad():
        for batch in data_loader:
            input_ids = batch["input_ids"].to(DEVICE)
            attention_mask = batch["attention_mask"].to(DEVICE)
            with torch.autocast(device_type=DEVICE.type, dtype=torch.float16, enabled=USE_AMP):
                logits = model(input_ids, attention_mask)
            output["t1"].append(sigmoid_numpy(logits[0].float().cpu().numpy()))
            output["t2"].append(softmax_numpy(logits[1].float().cpu().numpy()))
            output["t3"].append(sigmoid_numpy(logits[2].float().cpu().numpy()))
            output["t4"].append(softmax_numpy(logits[3].float().cpu().numpy()))
    return {task: np.concatenate(parts, axis=0) for task, parts in output.items()}


def probabilities_to_frame(df, probabilities):
    output = pd.DataFrame({ID_COLUMN: df[ID_COLUMN].values})
    output["t1__Yes"] = probabilities["t1"]
    output["t1__No"] = 1.0 - probabilities["t1"]
    output["t3__Yes"] = probabilities["t3"]
    output["t3__No"] = 1.0 - probabilities["t3"]
    for index, label in enumerate(TASK_CLASSES["t2"]):
        output[f"t2__{label}"] = probabilities["t2"][:, index]
    for index, label in enumerate(TASK_CLASSES["t4"]):
        output[f"t4__{label}"] = probabilities["t4"][:, index]
    return output


def argmax_label(row, task):
    labels = TASK_CLASSES[task]
    values = [row[f"{task}__{label}"] for label in labels]
    return labels[int(np.argmax(values))]


def route_predictions(probability_df, t1_threshold=0.5, t3_threshold=0.5):
    results = []
    for row_index, row in probability_df.iterrows():
        source_id = probability_df.at[row_index, ID_COLUMN]
        t1_prediction = "Yes" if row["t1__Yes"] >= t1_threshold else "No"
        if t1_prediction == "No":
            results.append(
                {
                    ID_COLUMN: source_id,
                    "promise_status": "No",
                    "verification_timeline": "N/A",
                    "evidence_status": "N/A",
                    "evidence_quality": "N/A",
                }
            )
            continue

        t2_prediction = argmax_label(row, "t2")
        t3_prediction = "Yes" if row["t3__Yes"] >= t3_threshold else "No"
        if t3_prediction == "No":
            results.append(
                {
                    ID_COLUMN: source_id,
                    "promise_status": "Yes",
                    "verification_timeline": t2_prediction,
                    "evidence_status": "No",
                    "evidence_quality": "N/A",
                }
            )
            continue

        results.append(
            {
                ID_COLUMN: source_id,
                "promise_status": "Yes",
                "verification_timeline": t2_prediction,
                "evidence_status": "Yes",
                "evidence_quality": argmax_label(row, "t4"),
            }
        )
    return pd.DataFrame(results)[[ID_COLUMN] + TARGET_COLUMNS]


def strict_task_f1(true_df, prediction_df, column):
    merged = true_df[[ID_COLUMN, column]].merge(
        prediction_df[[ID_COLUMN, column]],
        on=ID_COLUMN,
        suffixes=("_true", "_pred"),
        validate="one_to_one",
    )
    y_true = merged[f"{column}_true"].apply(normalize_value)
    y_pred = merged[f"{column}_pred"].apply(normalize_value)
    valid = y_true.notna()
    task = {
        "promise_status": "t1",
        "verification_timeline": "t2",
        "evidence_status": "t3",
        "evidence_quality": "t4",
    }[column]
    return f1_score(
        y_true[valid],
        y_pred[valid].fillna("N/A"),
        labels=TASK_CLASSES[task],
        average="macro",
        zero_division=0,
    )


def evaluate_submission(true_df, prediction_df):
    scores = {
        column: strict_task_f1(true_df, prediction_df, column)
        for column in TARGET_COLUMNS
    }
    competition_score = (
        TASK_WEIGHTS["t1"] * scores["promise_status"]
        + TASK_WEIGHTS["t2"] * scores["verification_timeline"]
        + TASK_WEIGHTS["t3"] * scores["evidence_status"]
        + TASK_WEIGHTS["t4"] * scores["evidence_quality"]
    )
    rows = [
        {"task": column, "macro_f1": score}
        for column, score in scores.items()
    ]
    rows.append({"task": "competition", "macro_f1": competition_score})
    return pd.DataFrame(rows)


def print_reports(true_df, prediction_df):
    for column in TARGET_COLUMNS:
        task = {
            "promise_status": "t1",
            "verification_timeline": "t2",
            "evidence_status": "t3",
            "evidence_quality": "t4",
        }[column]
        merged = true_df[[ID_COLUMN, column]].merge(
            prediction_df[[ID_COLUMN, column]],
            on=ID_COLUMN,
            suffixes=("_true", "_pred"),
        )
        y_true = merged[f"{column}_true"].apply(normalize_value)
        y_pred = merged[f"{column}_pred"].apply(normalize_value)
        valid = y_true.notna()
        labels = TASK_CLASSES[task]
        print(f"\n=== {column} ===")
        print(classification_report(
            y_true[valid],
            y_pred[valid].fillna("N/A"),
            labels=labels,
            zero_division=0,
        ))
        print(pd.DataFrame(
            confusion_matrix(
                y_true[valid],
                y_pred[valid].fillna("N/A"),
                labels=labels,
            ),
            index=labels,
            columns=labels,
        ))


def tune_routing_thresholds(true_df, probability_df):
    best = {
        "score": -1.0,
        "t1_threshold": 0.5,
        "t3_threshold": 0.5,
    }
    grid = np.round(np.arange(0.20, 0.801, 0.01), 2)
    for t1_threshold in grid:
        for t3_threshold in grid:
            prediction_df = route_predictions(
                probability_df,
                t1_threshold=t1_threshold,
                t3_threshold=t3_threshold,
            )
            metrics = evaluate_submission(true_df, prediction_df)
            score = float(metrics.loc[metrics["task"] == "competition", "macro_f1"].iloc[0])
            if score > best["score"]:
                best = {
                    "score": score,
                    "objective": "competition_macro_f1",
                    "t1_threshold": float(t1_threshold),
                    "t3_threshold": float(t3_threshold),
                }
    return best

In [7]:
# ==========================================
# 4. Training helpers
# ==========================================

def create_optimizer(model):
    no_decay = ["bias", "LayerNorm.weight"]
    parameter_groups = []
    for module, learning_rate in [
        (model.backbone, BACKBONE_LR),
        (nn.ModuleList([model.t1_head, model.t2_head, model.t3_head, model.t4_head]), HEAD_LR),
    ]:
        named_parameters = list(module.named_parameters())
        parameter_groups.extend(
            [
                {
                    "params": [
                        parameter
                        for name, parameter in named_parameters
                        if not any(token in name for token in no_decay)
                    ],
                    "lr": learning_rate,
                    "weight_decay": WEIGHT_DECAY,
                },
                {
                    "params": [
                        parameter
                        for name, parameter in named_parameters
                        if any(token in name for token in no_decay)
                    ],
                    "lr": learning_rate,
                    "weight_decay": 0.0,
                },
            ]
        )
    return torch.optim.AdamW(parameter_groups)


def save_checkpoint(model, path, fold, epoch, metrics):
    torch.save(
        {
            "artifact_version": 2,
            "model_name": MODEL_NAME,
            "max_len": MAX_LEN,
            "head_ratio": HEAD_RATIO,
            "fold": fold,
            "best_epoch": epoch,
            "metrics": metrics,
            "model_state_dict": model.state_dict(),
        },
        path,
    )


def load_checkpoint(model, path):
    checkpoint = torch.load(path, map_location=DEVICE)
    state_dict = checkpoint.get("model_state_dict", checkpoint)
    model.load_state_dict(state_dict)
    return checkpoint


def train_one_fold(fold, tokenizer):
    set_seed(SEED + fold)
    train_df = read_fold_csv(fold, "train")
    val_df = read_fold_csv(fold, "val")
    validate_training_frame(train_df, f"train_fold_{fold}")
    validate_training_frame(val_df, f"val_fold_{fold}")

    train_dataset = ESGMTLDataset(train_df, tokenizer)
    val_dataset = ESGMTLDataset(val_df, tokenizer)
    generator = torch.Generator().manual_seed(SEED + fold)
    train_loader = DataLoader(
        train_dataset,
        batch_size=BATCH_SIZE,
        shuffle=True,
        generator=generator,
        num_workers=0,
        pin_memory=USE_AMP,
    )
    val_loader = DataLoader(
        val_dataset,
        batch_size=BATCH_SIZE,
        shuffle=False,
        num_workers=0,
        pin_memory=USE_AMP,
    )

    model = ESGUnifiedMTLModel(MODEL_NAME).to(DEVICE)
    class_weights = compute_fold_class_weights(train_df)
    print("Class weights:", {
        task: np.round(weights.detach().cpu().numpy(), 3).tolist()
        for task, weights in class_weights.items()
    })

    optimizer = create_optimizer(model)
    optimizer_steps_per_epoch = math.ceil(len(train_loader) / GRAD_ACCUM_STEPS)
    total_steps = optimizer_steps_per_epoch * MAX_EPOCHS
    warmup_steps = max(1, int(total_steps * WARMUP_RATIO))
    scheduler = get_cosine_schedule_with_warmup(
        optimizer,
        num_warmup_steps=warmup_steps,
        num_training_steps=total_steps,
    )
    scaler = torch.amp.GradScaler("cuda", enabled=USE_AMP)

    fold_dir = OUTPUT_DIR / f"fold_{fold}"
    fold_dir.mkdir(parents=True, exist_ok=True)
    checkpoint_path = fold_dir / "best_model.pth"

    best_score = -1.0
    best_epoch = 0
    epochs_without_improvement = 0
    history = []

    for epoch in range(1, MAX_EPOCHS + 1):
        model.train()
        optimizer.zero_grad(set_to_none=True)
        epoch_loss = 0.0
        task_loss_sums = {task: 0.0 for task in TASK_WEIGHTS}

        for step, batch in enumerate(tqdm(train_loader, desc=f"Fold {fold} epoch {epoch}"), start=1):
            input_ids = batch["input_ids"].to(DEVICE)
            attention_mask = batch["attention_mask"].to(DEVICE)
            with torch.autocast(device_type=DEVICE.type, dtype=torch.float16, enabled=USE_AMP):
                predictions = model(input_ids, attention_mask)
                loss, task_losses = calculate_mtl_loss(predictions, batch, class_weights)
                scaled_loss = loss / GRAD_ACCUM_STEPS

            scaler.scale(scaled_loss).backward()
            if step % GRAD_ACCUM_STEPS == 0 or step == len(train_loader):
                scaler.unscale_(optimizer)
                torch.nn.utils.clip_grad_norm_(model.parameters(), MAX_GRAD_NORM)
                scaler.step(optimizer)
                scaler.update()
                scheduler.step()
                optimizer.zero_grad(set_to_none=True)

            epoch_loss += float(loss.detach().cpu())
            for task in task_loss_sums:
                task_loss_sums[task] += float(task_losses[task].detach().cpu())

        val_probabilities = predict_probabilities(model, val_loader)
        val_probability_df = probabilities_to_frame(val_df, val_probabilities)
        val_prediction_df = route_predictions(val_probability_df, 0.5, 0.5)
        val_metrics = evaluate_submission(
            val_df[[ID_COLUMN] + TARGET_COLUMNS],
            val_prediction_df,
        )
        val_score = float(
            val_metrics.loc[val_metrics["task"] == "competition", "macro_f1"].iloc[0]
        )
        row = {
            "fold": fold,
            "epoch": epoch,
            "train_loss": epoch_loss / len(train_loader),
            "competition_score": val_score,
        }
        for task in task_loss_sums:
            row[f"{task}_loss"] = task_loss_sums[task] / len(train_loader)
        for _, metric_row in val_metrics.iterrows():
            row[f"{metric_row['task']}_macro_f1"] = float(metric_row["macro_f1"])
        history.append(row)
        print(pd.DataFrame([row]).to_string(index=False))

        if val_score > best_score + MIN_SCORE_IMPROVEMENT:
            best_score = val_score
            best_epoch = epoch
            epochs_without_improvement = 0
            metrics_dict = {
                str(metric_row["task"]): float(metric_row["macro_f1"])
                for _, metric_row in val_metrics.iterrows()
            }
            save_checkpoint(
                model,
                checkpoint_path,
                fold=fold,
                epoch=epoch,
                metrics=metrics_dict,
            )
            print(f"Saved new best fold {fold} checkpoint: epoch={epoch}, score={val_score:.6f}")
        else:
            epochs_without_improvement += 1
            if epochs_without_improvement >= EARLY_STOPPING_PATIENCE:
                print(f"Early stopping fold {fold} after epoch {epoch}.")
                break

    history_df = pd.DataFrame(history)
    history_df.to_csv(fold_dir / "training_history.csv", index=False)

    checkpoint = load_checkpoint(model, checkpoint_path)
    if int(checkpoint["best_epoch"]) != best_epoch:
        raise RuntimeError("Loaded checkpoint does not match the tracked best epoch.")
    val_probabilities = predict_probabilities(model, val_loader)
    val_probability_df = probabilities_to_frame(val_df, val_probabilities)
    val_prediction_df = route_predictions(val_probability_df, 0.5, 0.5)
    print(f"\nFold {fold} best epoch: {best_epoch}")
    display(evaluate_submission(val_df[[ID_COLUMN] + TARGET_COLUMNS], val_prediction_df))
    print_reports(val_df[[ID_COLUMN] + TARGET_COLUMNS], val_prediction_df)

    del model
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()

    return (
        val_df[[ID_COLUMN] + TARGET_COLUMNS].copy(),
        val_probability_df,
        history_df,
    )

In [8]:
# ==========================================
# 5. Train exactly five folds and build OOF predictions
# ==========================================

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME, use_fast=True)
tokenizer.save_pretrained(TOKENIZER_DIR)

oof_truth_parts = []
oof_probability_parts = []
history_parts = []

for fold in FOLDS:
    print(f"\n{'=' * 60}\nTraining fold {fold}\n{'=' * 60}")
    fold_truth, fold_probabilities, fold_history = train_one_fold(fold, tokenizer)
    oof_truth_parts.append(fold_truth)
    oof_probability_parts.append(fold_probabilities)
    history_parts.append(fold_history)

oof_true_df = pd.concat(oof_truth_parts, ignore_index=True)
oof_probability_df = pd.concat(oof_probability_parts, ignore_index=True)
training_history_df = pd.concat(history_parts, ignore_index=True)

oof_probability_df.to_csv(OOF_PROBABILITY_CSV, index=False)
training_history_df.to_csv(OUTPUT_DIR / "training_history.csv", index=False)
print(f"Saved OOF probabilities to {OOF_PROBABILITY_CSV}")

============================================================
Training fold 1
============================================================

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] BertModel LOAD REPORT from: ckiplab/bert-base-chinese
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.decoder.weight             | UNEXPECTED |
cls.predictions.decoder.bias               | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
pooler.dense.weight                        | MISSING    |
pooler.dense.bias                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Class weights: {'t1': [2.0899999141693115, 1.0], 't2': [1.0, 4.5279998779296875, 1.1990000009536743, 1.38100004196167], 't3': [2.194000005722046, 1.0], 't4': [1.0, 2.2239999771118164, 4.681000232696533]}

Fold 1 epoch 1:   0%|          | 0/214 [00:00<?, ?it/s]

 fold  epoch  train_loss  competition_score  t1_loss  t2_loss  t3_loss  t4_loss  promise_status_macro_f1  verification_timeline_macro_f1  evidence_status_macro_f1  evidence_quality_macro_f1  competition_macro_f1
    1      1    0.955308           0.488675 0.615665 1.337601 0.634491 1.260537                 0.448276                        0.300379                  0.671425                   0.435816              0.488675
Saved new best fold 1 checkpoint: epoch=1, score=0.488675

Fold 1 epoch 2:   0%|          | 0/214 [00:00<?, ?it/s]

 fold  epoch  train_loss  competition_score  t1_loss  t2_loss  t3_loss  t4_loss  promise_status_macro_f1  verification_timeline_macro_f1  evidence_status_macro_f1  evidence_quality_macro_f1  competition_macro_f1
    1      2     0.72864           0.511227 0.538661 1.179708 0.503136 0.837175                     0.75                        0.351788                  0.705523                   0.276579              0.511227
Saved new best fold 1 checkpoint: epoch=2, score=0.511227

Fold 1 epoch 3:   0%|          | 0/214 [00:00<?, ?it/s]

 fold  epoch  train_loss  competition_score  t1_loss  t2_loss  t3_loss  t4_loss  promise_status_macro_f1  verification_timeline_macro_f1  evidence_status_macro_f1  evidence_quality_macro_f1  competition_macro_f1
    1      3     0.62902           0.533454 0.473988  1.04607 0.461029 0.682866                 0.731724                        0.517939                  0.689044                   0.293442              0.533454
Saved new best fold 1 checkpoint: epoch=3, score=0.533454

Fold 1 epoch 4:   0%|          | 0/214 [00:00<?, ?it/s]

 fold  epoch  train_loss  competition_score  t1_loss  t2_loss  t3_loss  t4_loss  promise_status_macro_f1  verification_timeline_macro_f1  evidence_status_macro_f1  evidence_quality_macro_f1  competition_macro_f1
    1      4    0.539471            0.58959 0.412107 0.934029 0.419532  0.54596                 0.726815                        0.557537                    0.7604                   0.378505               0.58959
Saved new best fold 1 checkpoint: epoch=4, score=0.589590

Fold 1 epoch 5:   0%|          | 0/214 [00:00<?, ?it/s]

 fold  epoch  train_loss  competition_score  t1_loss  t2_loss  t3_loss  t4_loss  promise_status_macro_f1  verification_timeline_macro_f1  evidence_status_macro_f1  evidence_quality_macro_f1  competition_macro_f1
    1      5     0.45223           0.592758 0.369204 0.835631 0.386765 0.391472                 0.769903                        0.566177                  0.749693                   0.368407              0.592758
Saved new best fold 1 checkpoint: epoch=5, score=0.592758

Fold 1 epoch 6:   0%|          | 0/214 [00:00<?, ?it/s]

 fold  epoch  train_loss  competition_score  t1_loss  t2_loss  t3_loss  t4_loss  promise_status_macro_f1  verification_timeline_macro_f1  evidence_status_macro_f1  evidence_quality_macro_f1  competition_macro_f1
    1      6     0.40439           0.601043  0.32958 0.781325 0.362345 0.321633                 0.755075                        0.600134                  0.767915                   0.370382              0.601043
Saved new best fold 1 checkpoint: epoch=6, score=0.601043

Fold 1 epoch 7:   0%|          | 0/214 [00:00<?, ?it/s]

 fold  epoch  train_loss  competition_score  t1_loss  t2_loss  t3_loss  t4_loss  promise_status_macro_f1  verification_timeline_macro_f1  evidence_status_macro_f1  evidence_quality_macro_f1  competition_macro_f1
    1      7    0.360918            0.61534 0.302898 0.734453 0.327243  0.26285                 0.755075                        0.628432                  0.761642                   0.404479               0.61534
Saved new best fold 1 checkpoint: epoch=7, score=0.615340

Fold 1 epoch 8:   0%|          | 0/214 [00:00<?, ?it/s]

 fold  epoch  train_loss  competition_score  t1_loss  t2_loss  t3_loss  t4_loss  promise_status_macro_f1  verification_timeline_macro_f1  evidence_status_macro_f1  evidence_quality_macro_f1  competition_macro_f1
    1      8    0.323195           0.607909 0.278837 0.656825 0.298558 0.226675                 0.755035                        0.627848                  0.761735                   0.383441              0.607909

Fold 1 epoch 9:   0%|          | 0/214 [00:00<?, ?it/s]

 fold  epoch  train_loss  competition_score  t1_loss  t2_loss  t3_loss  t4_loss  promise_status_macro_f1  verification_timeline_macro_f1  evidence_status_macro_f1  evidence_quality_macro_f1  competition_macro_f1
    1      9    0.317697           0.625526 0.271601 0.648618 0.291909 0.224319                 0.748884                        0.628389                  0.774249                   0.426332              0.625526
Saved new best fold 1 checkpoint: epoch=9, score=0.625526

Fold 1 epoch 10:   0%|          | 0/214 [00:00<?, ?it/s]

 fold  epoch  train_loss  competition_score  t1_loss  t2_loss  t3_loss  t4_loss  promise_status_macro_f1  verification_timeline_macro_f1  evidence_status_macro_f1  evidence_quality_macro_f1  competition_macro_f1
    1     10    0.309635           0.624997 0.271949 0.641809 0.279604  0.21455                 0.752009                        0.624767                  0.773219                   0.425469              0.624997

Fold 1 best epoch: 9

                    task  macro_f1
0         promise_status  0.748884
1  verification_timeline  0.628389
2        evidence_status  0.774249
3       evidence_quality  0.426332
4            competition  0.625526

=== promise_status ===
              precision    recall  f1-score   support

          No       0.70      0.49      0.58        75
         Yes       0.89      0.95      0.92       325

    accuracy                           0.86       400
   macro avg       0.79      0.72      0.75       400
weighted avg       0.85      0.86      0.86       400

     No  Yes
No   37   38
Yes  16  309

=== verification_timeline ===
                       precision    recall  f1-score   support

              already       0.66      0.56      0.61       144
       within_2_years       0.57      0.67      0.62         6
between_2_and_5_years       0.58      0.61      0.59        99
  longer_than_5_years       0.70      0.70      0.70        76

            micro avg       0.64      0.61      0.62       325
            macro avg       0.63      0.63      0.63       325
         weighted avg       0.64      0.61      0.62       325

                       already  within_2_years  between_2_and_5_years  \
already                     81               0                     34
within_2_years               2               4                      0
between_2_and_5_years       27               3                     60
longer_than_5_years         13               0                      9

                       longer_than_5_years
already                                 19
within_2_years                           0
between_2_and_5_years                    4
longer_than_5_years                     53

=== evidence_status ===
              precision    recall  f1-score   support

          No       0.73      0.57      0.64        58
         Yes       0.91      0.90      0.91       267

   micro avg       0.89      0.84      0.86       325
   macro avg       0.82      0.74      0.77       325
weighted avg       0.88      0.84      0.86       325

     No  Yes
No   33   23
Yes  12  241

=== evidence_quality ===
              precision    recall  f1-score   support

       Clear       0.91      0.86      0.88       223
   Not Clear       0.47      0.34      0.39        44
  Misleading       0.00      0.00      0.00         0

   micro avg       0.85      0.77      0.81       267
   macro avg       0.46      0.40      0.43       267
weighted avg       0.84      0.77      0.80       267

            Clear  Not Clear  Misleading
Clear         191         17           0
Not Clear      18         15           0
Misleading      0          0           0

============================================================
Training fold 2
============================================================

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] BertModel LOAD REPORT from: ckiplab/bert-base-chinese
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.decoder.weight             | UNEXPECTED |
cls.predictions.decoder.bias               | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
pooler.dense.weight                        | MISSING    |
pooler.dense.bias                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Class weights: {'t1': [2.0899999141693115, 1.0], 't2': [1.0, 4.5279998779296875, 1.1990000009536743, 1.38100004196167], 't3': [2.187999963760376, 1.0], 't4': [1.0, 2.2300000190734863, 4.681000232696533]}

Fold 2 epoch 1:   0%|          | 0/214 [00:00<?, ?it/s]

 fold  epoch  train_loss  competition_score  t1_loss  t2_loss  t3_loss  t4_loss  promise_status_macro_f1  verification_timeline_macro_f1  evidence_status_macro_f1  evidence_quality_macro_f1  competition_macro_f1
    2      1    0.948276           0.373527 0.619497 1.303454 0.576054 1.302979                 0.448276                        0.195001                  0.451939                   0.340114              0.373527
Saved new best fold 2 checkpoint: epoch=1, score=0.373527

Fold 2 epoch 2:   0%|          | 0/214 [00:00<?, ?it/s]

 fold  epoch  train_loss  competition_score  t1_loss  t2_loss  t3_loss  t4_loss  promise_status_macro_f1  verification_timeline_macro_f1  evidence_status_macro_f1  evidence_quality_macro_f1  competition_macro_f1
    2      2     0.79367           0.543424 0.580133 1.218997 0.497675 0.987118                 0.682411                        0.354124                  0.660155                   0.445075              0.543424
Saved new best fold 2 checkpoint: epoch=2, score=0.543424

Fold 2 epoch 3:   0%|          | 0/214 [00:00<?, ?it/s]

 fold  epoch  train_loss  competition_score  t1_loss  t2_loss  t3_loss  t4_loss  promise_status_macro_f1  verification_timeline_macro_f1  evidence_status_macro_f1  evidence_quality_macro_f1  competition_macro_f1
    2      3    0.677663           0.551403 0.525862 1.163763 0.472258  0.73214                 0.729778                        0.398498                  0.696741                   0.390429              0.551403
Saved new best fold 2 checkpoint: epoch=3, score=0.551403

Fold 2 epoch 4:   0%|          | 0/214 [00:00<?, ?it/s]

 fold  epoch  train_loss  competition_score  t1_loss  t2_loss  t3_loss  t4_loss  promise_status_macro_f1  verification_timeline_macro_f1  evidence_status_macro_f1  evidence_quality_macro_f1  competition_macro_f1
    2      4    0.609122           0.556646 0.471279  1.10888 0.439519 0.619081                 0.722489                        0.409394                  0.716344                   0.388103              0.556646
Saved new best fold 2 checkpoint: epoch=4, score=0.556646

Fold 2 epoch 5:   0%|          | 0/214 [00:00<?, ?it/s]

 fold  epoch  train_loss  competition_score  t1_loss  t2_loss  t3_loss  t4_loss  promise_status_macro_f1  verification_timeline_macro_f1  evidence_status_macro_f1  evidence_quality_macro_f1  competition_macro_f1
    2      5    0.552789           0.573235 0.437234 1.049681 0.406939 0.530881                 0.701879                        0.421535                  0.739065                   0.422597              0.573235
Saved new best fold 2 checkpoint: epoch=5, score=0.573235

Fold 2 epoch 6:   0%|          | 0/214 [00:00<?, ?it/s]

 fold  epoch  train_loss  competition_score  t1_loss  t2_loss  t3_loss  t4_loss  promise_status_macro_f1  verification_timeline_macro_f1  evidence_status_macro_f1  evidence_quality_macro_f1  competition_macro_f1
    2      6    0.504004           0.562804  0.41198 1.001653 0.391199 0.440002                 0.731775                         0.43903                  0.713826                   0.389847              0.562804

Fold 2 epoch 7:   0%|          | 0/214 [00:00<?, ?it/s]

 fold  epoch  train_loss  competition_score  t1_loss  t2_loss  t3_loss  t4_loss  promise_status_macro_f1  verification_timeline_macro_f1  evidence_status_macro_f1  evidence_quality_macro_f1  competition_macro_f1
    2      7    0.459155            0.57877 0.384518 0.941869 0.367135 0.373803                 0.714523                        0.429948                  0.736365                   0.429896               0.57877
Saved new best fold 2 checkpoint: epoch=7, score=0.578770

Fold 2 epoch 8:   0%|          | 0/214 [00:00<?, ?it/s]

 fold  epoch  train_loss  competition_score  t1_loss  t2_loss  t3_loss  t4_loss  promise_status_macro_f1  verification_timeline_macro_f1  evidence_status_macro_f1  evidence_quality_macro_f1  competition_macro_f1
    2      8    0.414044            0.57456 0.362956 0.890397 0.343278 0.299742                 0.711715                        0.448336                  0.733431                   0.414107               0.57456

Fold 2 epoch 9:   0%|          | 0/214 [00:00<?, ?it/s]

 fold  epoch  train_loss  competition_score  t1_loss  t2_loss  t3_loss  t4_loss  promise_status_macro_f1  verification_timeline_macro_f1  evidence_status_macro_f1  evidence_quality_macro_f1  competition_macro_f1
    2      9    0.399573           0.573103 0.357283 0.878472 0.330854 0.277397                 0.696078                        0.457746                  0.748924                   0.401566              0.573103
Early stopping fold 2 after epoch 9.

Fold 2 best epoch: 7

                    task  macro_f1
0         promise_status  0.714523
1  verification_timeline  0.429948
2        evidence_status  0.736365
3       evidence_quality  0.429896
4            competition  0.578770

=== promise_status ===
              precision    recall  f1-score   support

          No       0.63      0.44      0.52        75
         Yes       0.88      0.94      0.91       325

    accuracy                           0.85       400
   macro avg       0.76      0.69      0.71       400
weighted avg       0.83      0.85      0.84       400

     No  Yes
No   33   42
Yes  19  306

=== verification_timeline ===
                       precision    recall  f1-score   support

              already       0.65      0.51      0.57       144
       within_2_years       0.00      0.00      0.00         6
between_2_and_5_years       0.56      0.57      0.56        99
  longer_than_5_years       0.53      0.64      0.58        76

            micro avg       0.58      0.55      0.57       325
            macro avg       0.44      0.43      0.43       325
         weighted avg       0.58      0.55      0.56       325

                       already  within_2_years  between_2_and_5_years  \
already                     74               0                     38
within_2_years               1               0                      0
between_2_and_5_years       21               0                     56
longer_than_5_years         18               0                      6

                       longer_than_5_years
already                                 21
within_2_years                           4
between_2_and_5_years                   18
longer_than_5_years                     49

=== evidence_status ===
              precision    recall  f1-score   support

          No       0.59      0.56      0.58        57
         Yes       0.92      0.87      0.90       268

   micro avg       0.87      0.82      0.84       325
   macro avg       0.76      0.72      0.74       325
weighted avg       0.87      0.82      0.84       325

     No  Yes
No   32   19
Yes  22  233

=== evidence_quality ===
              precision    recall  f1-score   support

       Clear       0.93      0.83      0.88       223
   Not Clear       0.48      0.36      0.41        45
  Misleading       0.00      0.00      0.00         0

   micro avg       0.87      0.75      0.81       268
   macro avg       0.47      0.40      0.43       268
weighted avg       0.86      0.75      0.80       268

            Clear  Not Clear  Misleading
Clear         186         17           0
Not Clear      14         16           0
Misleading      0          0           0

============================================================
Training fold 3
============================================================

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] BertModel LOAD REPORT from: ckiplab/bert-base-chinese
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.decoder.weight             | UNEXPECTED |
cls.predictions.decoder.bias               | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
pooler.dense.weight                        | MISSING    |
pooler.dense.bias                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Class weights: {'t1': [2.0859999656677246, 1.0], 't2': [1.0, 4.703000068664551, 1.2020000219345093, 1.3799999952316284], 't3': [2.180999994277954, 1.0], 't4': [1.0, 2.234999895095825, 4.677999973297119]}

Fold 3 epoch 1:   0%|          | 0/214 [00:00<?, ?it/s]

 fold  epoch  train_loss  competition_score  t1_loss  t2_loss  t3_loss  t4_loss  promise_status_macro_f1  verification_timeline_macro_f1  evidence_status_macro_f1  evidence_quality_macro_f1  competition_macro_f1
    3      1    0.943649           0.443985   0.6168 1.266639 0.587124 1.297589                 0.449036                        0.382687                   0.45302                   0.459625              0.443985
Saved new best fold 3 checkpoint: epoch=1, score=0.443985

Fold 3 epoch 2:   0%|          | 0/214 [00:00<?, ?it/s]

 fold  epoch  train_loss  competition_score  t1_loss  t2_loss  t3_loss  t4_loss  promise_status_macro_f1  verification_timeline_macro_f1  evidence_status_macro_f1  evidence_quality_macro_f1  competition_macro_f1
    3      2    0.740162           0.509755 0.517036 1.155049 0.503758 0.892486                 0.654676                        0.390571                  0.677648                   0.334112              0.509755
Saved new best fold 3 checkpoint: epoch=2, score=0.509755

Fold 3 epoch 3:   0%|          | 0/214 [00:00<?, ?it/s]

 fold  epoch  train_loss  competition_score  t1_loss  t2_loss  t3_loss  t4_loss  promise_status_macro_f1  verification_timeline_macro_f1  evidence_status_macro_f1  evidence_quality_macro_f1  competition_macro_f1
    3      3    0.605086           0.546545 0.434456 1.052192 0.465689 0.630455                 0.760264                        0.409963                  0.709078                   0.343642              0.546545
Saved new best fold 3 checkpoint: epoch=3, score=0.546545

Fold 3 epoch 4:   0%|          | 0/214 [00:00<?, ?it/s]

 fold  epoch  train_loss  competition_score  t1_loss  t2_loss  t3_loss  t4_loss  promise_status_macro_f1  verification_timeline_macro_f1  evidence_status_macro_f1  evidence_quality_macro_f1  competition_macro_f1
    3      4    0.515361           0.556885 0.374318 0.949181 0.436928 0.477261                 0.764108                         0.55483                   0.65194                   0.357877              0.556885
Saved new best fold 3 checkpoint: epoch=4, score=0.556885

Fold 3 epoch 5:   0%|          | 0/214 [00:00<?, ?it/s]

 fold  epoch  train_loss  competition_score  t1_loss  t2_loss  t3_loss  t4_loss  promise_status_macro_f1  verification_timeline_macro_f1  evidence_status_macro_f1  evidence_quality_macro_f1  competition_macro_f1
    3      5    0.439329           0.558554 0.321823 0.851563 0.401963 0.361833                 0.727768                        0.607401                  0.671336                   0.344255              0.558554
Saved new best fold 3 checkpoint: epoch=5, score=0.558554

Fold 3 epoch 6:   0%|          | 0/214 [00:00<?, ?it/s]

 fold  epoch  train_loss  competition_score  t1_loss  t2_loss  t3_loss  t4_loss  promise_status_macro_f1  verification_timeline_macro_f1  evidence_status_macro_f1  evidence_quality_macro_f1  competition_macro_f1
    3      6    0.387317           0.564587 0.292735 0.781137 0.380918 0.278069                 0.774892                        0.622634                  0.652597                   0.344098              0.564587
Saved new best fold 3 checkpoint: epoch=6, score=0.564587

Fold 3 epoch 7:   0%|          | 0/214 [00:00<?, ?it/s]

 fold  epoch  train_loss  competition_score  t1_loss  t2_loss  t3_loss  t4_loss  promise_status_macro_f1  verification_timeline_macro_f1  evidence_status_macro_f1  evidence_quality_macro_f1  competition_macro_f1
    3      7    0.350586           0.563759 0.263277 0.708757 0.350009 0.247471                 0.752004                        0.645494                    0.6404                   0.355467              0.563759

Fold 3 epoch 8:   0%|          | 0/214 [00:00<?, ?it/s]

 fold  epoch  train_loss  competition_score  t1_loss  t2_loss  t3_loss  t4_loss  promise_status_macro_f1  verification_timeline_macro_f1  evidence_status_macro_f1  evidence_quality_macro_f1  competition_macro_f1
    3      8    0.323716           0.573638 0.252985 0.635428 0.332679 0.222861                 0.748537                        0.649525                  0.667989                   0.360302              0.573638
Saved new best fold 3 checkpoint: epoch=8, score=0.573638

Fold 3 epoch 9:   0%|          | 0/214 [00:00<?, ?it/s]

 fold  epoch  train_loss  competition_score  t1_loss  t2_loss  t3_loss  t4_loss  promise_status_macro_f1  verification_timeline_macro_f1  evidence_status_macro_f1  evidence_quality_macro_f1  competition_macro_f1
    3      9    0.307461           0.583108 0.243348 0.616243 0.314624 0.205623                 0.758222                        0.656306                  0.652253                   0.392404              0.583108
Saved new best fold 3 checkpoint: epoch=9, score=0.583108

Fold 3 epoch 10:   0%|          | 0/214 [00:00<?, ?it/s]

 fold  epoch  train_loss  competition_score  t1_loss  t2_loss  t3_loss  t4_loss  promise_status_macro_f1  verification_timeline_macro_f1  evidence_status_macro_f1  evidence_quality_macro_f1  competition_macro_f1
    3     10    0.297992           0.586053 0.236292 0.599704 0.307081 0.196154                 0.761405                        0.654423                  0.659703                   0.393422              0.586053
Saved new best fold 3 checkpoint: epoch=10, score=0.586053

Fold 3 best epoch: 10

                    task  macro_f1
0         promise_status  0.761405
1  verification_timeline  0.654423
2        evidence_status  0.659703
3       evidence_quality  0.393422
4            competition  0.586053

=== promise_status ===
              precision    recall  f1-score   support

          No       0.74      0.50      0.60        74
         Yes       0.89      0.96      0.93       326

    accuracy                           0.88       400
   macro avg       0.82      0.73      0.76       400
weighted avg       0.87      0.88      0.87       400

     No  Yes
No   37   37
Yes  13  313

=== verification_timeline ===
                       precision    recall  f1-score   support

              already       0.70      0.66      0.68       143
       within_2_years       0.80      0.50      0.62         8
between_2_and_5_years       0.60      0.55      0.57       100
  longer_than_5_years       0.72      0.77      0.75        75

            micro avg       0.68      0.65      0.66       326
            macro avg       0.71      0.62      0.65       326
         weighted avg       0.68      0.65      0.66       326

                       already  within_2_years  between_2_and_5_years  \
already                     95               0                     26
within_2_years               2               4                      1
between_2_and_5_years       32               1                     55
longer_than_5_years          7               0                     10

                       longer_than_5_years
already                                 13
within_2_years                           1
between_2_and_5_years                    8
longer_than_5_years                     58

=== evidence_status ===
              precision    recall  f1-score   support

          No       0.50      0.39      0.44        56
         Yes       0.88      0.88      0.88       270

   micro avg       0.83      0.79      0.81       326
   macro avg       0.69      0.64      0.66       326
weighted avg       0.82      0.79      0.80       326

     No  Yes
No   22   32
Yes  22  237

=== evidence_quality ===
              precision    recall  f1-score   support

       Clear       0.91      0.87      0.89       224
   Not Clear       0.43      0.22      0.29        46
  Misleading       0.00      0.00      0.00         0

   micro avg       0.86      0.76      0.81       270
   macro avg       0.45      0.36      0.39       270
weighted avg       0.83      0.76      0.79       270

            Clear  Not Clear  Misleading
Clear         195         13           0
Not Clear      19         10           0
Misleading      0          0           0

============================================================
Training fold 4
============================================================

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] BertModel LOAD REPORT from: ckiplab/bert-base-chinese
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.decoder.weight             | UNEXPECTED |
cls.predictions.decoder.bias               | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
pooler.dense.weight                        | MISSING    |
pooler.dense.bias                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Class weights: {'t1': [2.0859999656677246, 1.0], 't2': [1.0, 4.611000061035156, 1.2009999752044678, 1.378999948501587], 't3': [2.180999994277954, 1.0], 't4': [1.0, 2.2290000915527344, 4.736000061035156]}

Fold 4 epoch 1:   0%|          | 0/214 [00:00<?, ?it/s]

 fold  epoch  train_loss  competition_score  t1_loss  t2_loss  t3_loss  t4_loss  promise_status_macro_f1  verification_timeline_macro_f1  evidence_status_macro_f1  evidence_quality_macro_f1  competition_macro_f1
    4      1    0.980423           0.416157 0.605251 1.334315 0.585228 1.381877                 0.449036                        0.344731                   0.45302                   0.396383              0.416157
Saved new best fold 4 checkpoint: epoch=1, score=0.416157

Fold 4 epoch 2:   0%|          | 0/214 [00:00<?, ?it/s]

 fold  epoch  train_loss  competition_score  t1_loss  t2_loss  t3_loss  t4_loss  promise_status_macro_f1  verification_timeline_macro_f1  evidence_status_macro_f1  evidence_quality_macro_f1  competition_macro_f1
    4      2    0.740434           0.500634  0.52826 1.194889 0.482012 0.888415                 0.704698                        0.319892                   0.67488                   0.312132              0.500634
Saved new best fold 4 checkpoint: epoch=2, score=0.500634

Fold 4 epoch 3:   0%|          | 0/214 [00:00<?, ?it/s]

 fold  epoch  train_loss  competition_score  t1_loss  t2_loss  t3_loss  t4_loss  promise_status_macro_f1  verification_timeline_macro_f1  evidence_status_macro_f1  evidence_quality_macro_f1  competition_macro_f1
    4      3     0.61645           0.508767 0.448683 1.137405 0.454335 0.628005                 0.784859                        0.374273                  0.654211                   0.283973              0.508767
Saved new best fold 4 checkpoint: epoch=3, score=0.508767

Fold 4 epoch 4:   0%|          | 0/214 [00:00<?, ?it/s]

 fold  epoch  train_loss  competition_score  t1_loss  t2_loss  t3_loss  t4_loss  promise_status_macro_f1  verification_timeline_macro_f1  evidence_status_macro_f1  evidence_quality_macro_f1  competition_macro_f1
    4      4    0.517953           0.559747 0.389996 1.014687 0.427684 0.455559                  0.81513                        0.419577                  0.692704                   0.359922              0.559747
Saved new best fold 4 checkpoint: epoch=4, score=0.559747

Fold 4 epoch 5:   0%|          | 0/214 [00:00<?, ?it/s]

 fold  epoch  train_loss  competition_score  t1_loss  t2_loss  t3_loss  t4_loss  promise_status_macro_f1  verification_timeline_macro_f1  evidence_status_macro_f1  evidence_quality_macro_f1  competition_macro_f1
    4      5     0.45116           0.566344 0.352599 0.920446 0.389063 0.359584                 0.790921                        0.447278                  0.713559                   0.362859              0.566344
Saved new best fold 4 checkpoint: epoch=5, score=0.566344

Fold 4 epoch 6:   0%|          | 0/214 [00:00<?, ?it/s]

 fold  epoch  train_loss  competition_score  t1_loss  t2_loss  t3_loss  t4_loss  promise_status_macro_f1  verification_timeline_macro_f1  evidence_status_macro_f1  evidence_quality_macro_f1  competition_macro_f1
    4      6    0.387714           0.568485 0.299001 0.822851 0.358075 0.277326                 0.794612                        0.462686                  0.705939                   0.366794              0.568485
Saved new best fold 4 checkpoint: epoch=6, score=0.568485

Fold 4 epoch 7:   0%|          | 0/214 [00:00<?, ?it/s]

 fold  epoch  train_loss  competition_score  t1_loss  t2_loss  t3_loss  t4_loss  promise_status_macro_f1  verification_timeline_macro_f1  evidence_status_macro_f1  evidence_quality_macro_f1  competition_macro_f1
    4      7    0.344377           0.565598 0.278393 0.745862  0.33659  0.21669                 0.800866                        0.442521                  0.707795                   0.362024              0.565598

Fold 4 epoch 8:   0%|          | 0/214 [00:00<?, ?it/s]

 fold  epoch  train_loss  competition_score  t1_loss  t2_loss  t3_loss  t4_loss  promise_status_macro_f1  verification_timeline_macro_f1  evidence_status_macro_f1  evidence_quality_macro_f1  competition_macro_f1
    4      8    0.314073           0.579912 0.256428 0.684348 0.310158 0.191679                 0.803074                        0.549748                  0.702834                   0.359957              0.579912
Saved new best fold 4 checkpoint: epoch=8, score=0.579912

Fold 4 epoch 9:   0%|          | 0/214 [00:00<?, ?it/s]

 fold  epoch  train_loss  competition_score  t1_loss  t2_loss  t3_loss  t4_loss  promise_status_macro_f1  verification_timeline_macro_f1  evidence_status_macro_f1  evidence_quality_macro_f1  competition_macro_f1
    4      9    0.303962           0.585675 0.242527 0.661119 0.306696 0.183658                 0.799499                        0.547547                  0.709806                   0.373432              0.585675
Saved new best fold 4 checkpoint: epoch=9, score=0.585675

Fold 4 epoch 10:   0%|          | 0/214 [00:00<?, ?it/s]

 fold  epoch  train_loss  competition_score  t1_loss  t2_loss  t3_loss  t4_loss  promise_status_macro_f1  verification_timeline_macro_f1  evidence_status_macro_f1  evidence_quality_macro_f1  competition_macro_f1
    4     10    0.291742           0.576601 0.238691 0.643452 0.296567 0.167188                 0.799499                        0.545309                  0.699356                   0.357422              0.576601

Fold 4 best epoch: 9

                    task  macro_f1
0         promise_status  0.799499
1  verification_timeline  0.547547
2        evidence_status  0.709806
3       evidence_quality  0.373432
4            competition  0.585675

=== promise_status ===
              precision    recall  f1-score   support

          No       0.74      0.61      0.67        74
         Yes       0.91      0.95      0.93       326

    accuracy                           0.89       400
   macro avg       0.83      0.78      0.80       400
weighted avg       0.88      0.89      0.88       400

     No  Yes
No   45   29
Yes  16  310

=== verification_timeline ===
                       precision    recall  f1-score   support

              already       0.70      0.54      0.61       144
       within_2_years       0.40      0.29      0.33         7
between_2_and_5_years       0.56      0.64      0.60       100
  longer_than_5_years       0.63      0.67      0.65        75

            micro avg       0.63      0.60      0.61       326
            macro avg       0.57      0.53      0.55       326
         weighted avg       0.63      0.60      0.61       326

                       already  within_2_years  between_2_and_5_years  \
already                     78               1                     33
within_2_years               2               2                      2
between_2_and_5_years       24               0                     64
longer_than_5_years          8               2                     15

                       longer_than_5_years
already                                 22
within_2_years                           0
between_2_and_5_years                    7
longer_than_5_years                     50

=== evidence_status ===
              precision    recall  f1-score   support

          No       0.56      0.52      0.54        56
         Yes       0.90      0.86      0.88       270

   micro avg       0.85      0.80      0.82       326
   macro avg       0.73      0.69      0.71       326
weighted avg       0.84      0.80      0.82       326

     No  Yes
No   29   25
Yes  23  233

=== evidence_quality ===
              precision    recall  f1-score   support

       Clear       0.90      0.85      0.87       224
   Not Clear       0.40      0.18      0.25        45
  Misleading       0.00      0.00      0.00         1

   micro avg       0.85      0.74      0.79       270
   macro avg       0.43      0.34      0.37       270
weighted avg       0.81      0.74      0.77       270

            Clear  Not Clear  Misleading
Clear         191         12           0
Not Clear      21          8           0
Misleading      1          0           0

============================================================
Training fold 5
============================================================

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] BertModel LOAD REPORT from: ckiplab/bert-base-chinese
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.decoder.weight             | UNEXPECTED |
cls.predictions.decoder.bias               | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
pooler.dense.weight                        | MISSING    |
pooler.dense.bias                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Class weights: {'t1': [2.0899999141693115, 1.0], 't2': [1.0, 4.614999771118164, 1.2020000219345093, 1.3799999952316284], 't3': [2.1760001182556152, 1.0], 't4': [1.0, 2.2290000915527344, 4.736000061035156]}

Fold 5 epoch 1:   0%|          | 0/214 [00:00<?, ?it/s]

 fold  epoch  train_loss  competition_score  t1_loss  t2_loss  t3_loss  t4_loss  promise_status_macro_f1  verification_timeline_macro_f1  evidence_status_macro_f1  evidence_quality_macro_f1  competition_macro_f1
    5      1    0.916969           0.466442 0.604787 1.293695 0.573844 1.228012                 0.462053                        0.251576                  0.708409                   0.353635              0.466442
Saved new best fold 5 checkpoint: epoch=1, score=0.466442

Fold 5 epoch 2:   0%|          | 0/214 [00:00<?, ?it/s]

 fold  epoch  train_loss  competition_score  t1_loss  t2_loss  t3_loss  t4_loss  promise_status_macro_f1  verification_timeline_macro_f1  evidence_status_macro_f1  evidence_quality_macro_f1  competition_macro_f1
    5      2     0.68835           0.510153   0.5096 1.197046 0.476249 0.754282                 0.682411                        0.412031                  0.659566                   0.325704              0.510153
Saved new best fold 5 checkpoint: epoch=2, score=0.510153

Fold 5 epoch 3:   0%|          | 0/214 [00:00<?, ?it/s]

 fold  epoch  train_loss  competition_score  t1_loss  t2_loss  t3_loss  t4_loss  promise_status_macro_f1  verification_timeline_macro_f1  evidence_status_macro_f1  evidence_quality_macro_f1  competition_macro_f1
    5      3     0.59692           0.542727 0.460923 1.121752 0.436504 0.587203                 0.727354                        0.416968                  0.636227                    0.41098              0.542727
Saved new best fold 5 checkpoint: epoch=3, score=0.542727

Fold 5 epoch 4:   0%|          | 0/214 [00:00<?, ?it/s]

 fold  epoch  train_loss  competition_score  t1_loss  t2_loss  t3_loss  t4_loss  promise_status_macro_f1  verification_timeline_macro_f1  evidence_status_macro_f1  evidence_quality_macro_f1  competition_macro_f1
    5      4    0.535218            0.57709 0.391538 1.017856 0.419644  0.50954                 0.745098                        0.455706                  0.729807                   0.402205               0.57709
Saved new best fold 5 checkpoint: epoch=4, score=0.577090

Fold 5 epoch 5:   0%|          | 0/214 [00:00<?, ?it/s]

 fold  epoch  train_loss  competition_score  t1_loss  t2_loss  t3_loss  t4_loss  promise_status_macro_f1  verification_timeline_macro_f1  evidence_status_macro_f1  evidence_quality_macro_f1  competition_macro_f1
    5      5    0.458583           0.557263 0.353644 0.930382 0.381247 0.382638                 0.754625                        0.462476                   0.69015                   0.371206              0.557263

Fold 5 epoch 6:   0%|          | 0/214 [00:00<?, ?it/s]

 fold  epoch  train_loss  competition_score  t1_loss  t2_loss  t3_loss  t4_loss  promise_status_macro_f1  verification_timeline_macro_f1  evidence_status_macro_f1  evidence_quality_macro_f1  competition_macro_f1
    5      6    0.398946           0.563441 0.319261 0.855502 0.334074 0.304418                 0.762873                        0.482233                  0.708519                   0.359931              0.563441
Early stopping fold 5 after epoch 6.

Fold 5 best epoch: 4

                    task  macro_f1
0         promise_status  0.745098
1  verification_timeline  0.455706
2        evidence_status  0.729807
3       evidence_quality  0.402205
4            competition  0.577090

=== promise_status ===
              precision    recall  f1-score   support

          No       0.76      0.45      0.57        75
         Yes       0.88      0.97      0.92       325

    accuracy                           0.87       400
   macro avg       0.82      0.71      0.75       400
weighted avg       0.86      0.87      0.86       400

     No  Yes
No   34   41
Yes  11  314

=== verification_timeline ===
                       precision    recall  f1-score   support

              already       0.62      0.71      0.66       143
       within_2_years       0.00      0.00      0.00         7
between_2_and_5_years       0.60      0.52      0.56       100
  longer_than_5_years       0.67      0.56      0.61        75

            micro avg       0.62      0.60      0.61       325
            macro avg       0.47      0.45      0.46       325
         weighted avg       0.61      0.60      0.60       325

                       already  within_2_years  between_2_and_5_years  \
already                    101               0                     24
within_2_years               2               0                      0
between_2_and_5_years       41               0                     52
longer_than_5_years         20               0                     11

                       longer_than_5_years
already                                 11
within_2_years                           5
between_2_and_5_years                    5
longer_than_5_years                     42

=== evidence_status ===
              precision    recall  f1-score   support

          No       0.67      0.47      0.55        55
         Yes       0.90      0.91      0.91       270

   micro avg       0.87      0.84      0.85       325
   macro avg       0.78      0.69      0.73       325
weighted avg       0.86      0.84      0.85       325

     No  Yes
No   26   28
Yes  13  247

=== evidence_quality ===
              precision    recall  f1-score   support

       Clear       0.88      0.92      0.90       224
   Not Clear       0.64      0.20      0.31        45
  Misleading       0.00      0.00      0.00         1

   micro avg       0.87      0.80      0.83       270
   macro avg       0.51      0.37      0.40       270
weighted avg       0.84      0.80      0.80       270

            Clear  Not Clear  Misleading
Clear         206          5           0
Not Clear      27          9           0
Misleading      0          0           0
Saved OOF probabilities to mtl_outputs/mtl_oof_probabilities.csv

In [9]:
# ==========================================
# 6. Tune routing thresholds and report final OOF metrics
# ==========================================

best_thresholds = tune_routing_thresholds(oof_true_df, oof_probability_df)
with open(THRESHOLD_JSON, "w", encoding="utf-8") as file:
    json.dump(best_thresholds, file, ensure_ascii=False, indent=2)
print("Best OOF routing thresholds:", best_thresholds)

oof_prediction_df = route_predictions(
    oof_probability_df,
    t1_threshold=best_thresholds["t1_threshold"],
    t3_threshold=best_thresholds["t3_threshold"],
)
oof_prediction_df.to_csv(OOF_PREDICTION_CSV, index=False)

oof_metrics = evaluate_submission(oof_true_df, oof_prediction_df)
display(oof_metrics)
print_reports(oof_true_df, oof_prediction_df)

Best OOF routing thresholds: {'score': 0.6011399224663667, 'objective': 'competition_macro_f1', 't1_threshold': 0.41, 't3_threshold': 0.35}

                    task  macro_f1
0         promise_status  0.754363
1  verification_timeline  0.565558
2        evidence_status  0.724977
3       evidence_quality  0.422687
4            competition  0.601140

=== promise_status ===
              precision    recall  f1-score   support

          No       0.75      0.48      0.58       373
         Yes       0.89      0.96      0.92      1627

    accuracy                           0.87      2000
   macro avg       0.82      0.72      0.75      2000
weighted avg       0.86      0.87      0.86      2000

      No   Yes
No   179   194
Yes   61  1566

=== verification_timeline ===
                       precision    recall  f1-score   support

              already       0.66      0.61      0.63       718
       within_2_years       0.59      0.29      0.39        34
between_2_and_5_years       0.58      0.58      0.58       498
  longer_than_5_years       0.65      0.67      0.66       377

            micro avg       0.63      0.61      0.62      1627
            macro avg       0.62      0.54      0.57      1627
         weighted avg       0.63      0.61      0.62      1627

                       already  within_2_years  between_2_and_5_years  \
already                    435               1                    155
within_2_years               9              10                      4
between_2_and_5_years      149               4                    290
longer_than_5_years         66               2                     51

                       longer_than_5_years
already                                 86
within_2_years                          10
between_2_and_5_years                   42
longer_than_5_years                    252

=== evidence_status ===
              precision    recall  f1-score   support

          No       0.68      0.46      0.55       282
         Yes       0.89      0.91      0.90      1345

   micro avg       0.87      0.83      0.85      1627
   macro avg       0.79      0.69      0.72      1627
weighted avg       0.86      0.83      0.84      1627

      No   Yes
No   129   147
Yes   61  1229

=== evidence_quality ===
              precision    recall  f1-score   support

       Clear       0.91      0.87      0.89      1118
   Not Clear       0.47      0.32      0.38       225
  Misleading       0.00      0.00      0.00         2

   micro avg       0.85      0.78      0.81      1345
   macro avg       0.46      0.40      0.42      1345
weighted avg       0.83      0.78      0.80      1345

            Clear  Not Clear  Misleading
Clear         977         79           0
Not Clear     101         71           0
Misleading      1          0           0

In [12]:
from huggingface_hub import HfApi, login, create_repo
import os
from huggingface_hub import notebook_login

notebook_login()

In [18]:
# ==========================================
# 7. Save inference config and optionally upload artifacts
# ==========================================

def save_inference_config():
    thresholds = {"t1_threshold": 0.5, "t3_threshold": 0.5}
    if THRESHOLD_JSON.exists():
        with open(THRESHOLD_JSON, "r", encoding="utf-8") as file:
            thresholds.update(json.load(file))

    config = {
        "artifact_version": 2,
        "model_type": "ckip_bert_multi_task_mlp",
        "model_name": MODEL_NAME,
        "folds": FOLDS,
        "max_len": MAX_LEN,
        "head_ratio": HEAD_RATIO,
        "task_classes": TASK_CLASSES,
        "target_columns": TARGET_COLUMNS,
        "task_weights": TASK_WEIGHTS,
        "probability_ensemble": True,
        "thresholds": thresholds,
        "synthetic_policy": {
            "id_min": SYNTHETIC_ID_MIN,
            "t4_sample_weight": SYNTHETIC_T4_SAMPLE_WEIGHT,
            "tasks": ["t4"],
        },
        "artifact_layout": {
            "checkpoint": "fold_{fold}/best_model.pth",
            "tokenizer": "tokenizer/",
            "thresholds": "mtl_thresholds.json",
        },
    }
    with open(INFERENCE_CONFIG_JSON, "w", encoding="utf-8") as file:
        json.dump(config, file, ensure_ascii=False, indent=2)
    return config


def validate_artifacts():
    missing = []
    for fold in FOLDS:
        checkpoint = OUTPUT_DIR / f"fold_{fold}" / "best_model.pth"
        if not checkpoint.exists():
            missing.append(str(checkpoint))
    for path in [TOKENIZER_DIR, THRESHOLD_JSON, INFERENCE_CONFIG_JSON]:
        if not Path(path).exists():
            missing.append(str(path))
    if missing:
        raise FileNotFoundError("Missing MTL artifacts: " + ", ".join(missing))


def resolve_hf_repo_id(api, repo_id=None):
    if repo_id:
        return repo_id
    return f"{api.whoami()['name']}/maxbeettww/VeriPromise_ESG_2026_9906"


def push_artifacts_to_hf(repo_id=None, private=HF_PRIVATE_REPO):
    save_inference_config()
    validate_artifacts()
    api = HfApi()
    resolved_repo_id = resolve_hf_repo_id(api, repo_id)
    api.create_repo(
        repo_id=resolved_repo_id,
        repo_type="model",
        private=private,
        exist_ok=True,
    )
    api.upload_folder(
        folder_path=str(OUTPUT_DIR),
        repo_id=resolved_repo_id,
        repo_type="model",
        commit_message=HF_COMMIT_MESSAGE,
    )
    print(f"Uploaded CKIP-BERT MTL artifacts: https://huggingface.co/{resolved_repo_id}")
    return resolved_repo_id


inference_config = save_inference_config()
print(json.dumps(inference_config, ensure_ascii=False, indent=2))

if RUN_HF_UPLOAD:
    notebook_login()
    uploaded_repo_id = push_artifacts_to_hf(HF_MTL_REPO_ID)
else:
    print("RUN_HF_UPLOAD is False. Set it to True after training to upload mtl_outputs.")

{
  "artifact_version": 2,
  "model_type": "ckip_bert_multi_task_mlp",
  "model_name": "ckiplab/bert-base-chinese",
  "folds": [
    1,
    2,
    3,
    4,
    5
  ],
  "max_len": 512,
  "head_ratio": 0.25,
  "task_classes": {
    "t1": [
      "No",
      "Yes"
    ],
    "t2": [
      "already",
      "within_2_years",
      "between_2_and_5_years",
      "longer_than_5_years"
    ],
    "t3": [
      "No",
      "Yes"
    ],
    "t4": [
      "Clear",
      "Not Clear",
      "Misleading"
    ]
  },
  "target_columns": [
    "promise_status",
    "verification_timeline",
    "evidence_status",
    "evidence_quality"
  ],
  "task_weights": {
    "t1": 0.2,
    "t2": 0.15,
    "t3": 0.3,
    "t4": 0.35
  },
  "probability_ensemble": true,
  "thresholds": {
    "t1_threshold": 0.41,
    "t3_threshold": 0.35,
    "score": 0.6011399224663667,
    "objective": "competition_macro_f1"
  },
  "synthetic_policy": {
    "id_min": 90000,
    "t4_sample_weight": 0.35,
    "tasks": [
      "t4"
    ]
  },
  "artifact_layout": {
    "checkpoint": "fold_{fold}/best_model.pth",
    "tokenizer": "tokenizer/",
    "thresholds": "mtl_thresholds.json"
  }
}

Processing Files (0 / 0): |          |  0.00B /  0.00B

New Data Upload: |          |  0.00B /  0.00B

Uploaded CKIP-BERT MTL artifacts: https://huggingface.co/maxbeettww/VeriPromise_ESG_2026_9906